/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smartek.productapp;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	Product p = new Product("Realme GT 2","Mobile",35000.0);
	System.out.println(p.name);
	System.out.println(p.description);
	System.out.println(p.price);
    }
}
